In [1]:
import pandas as pd
import numpy as np

In [2]:
gameInput = pd.read_csv("./../../data/raw/game.csv").dropna().sort_values(by=['date_time_GMT'])
goalieInput = pd.read_csv("./../../data/raw/game_goalie_stats.csv")
skaterStatsInput = pd.read_csv("./../../data/raw/game_skater_stats.csv")

In [4]:
skaterStatsInput.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411578 entries, 0 to 411577
Data columns (total 22 columns):
game_id                 411578 non-null int64
player_id               411578 non-null int64
team_id                 411578 non-null int64
timeOnIce               411578 non-null int64
assists                 411578 non-null int64
goals                   411578 non-null int64
shots                   411578 non-null int64
hits                    411578 non-null int64
powerPlayGoals          411578 non-null int64
powerPlayAssists        411578 non-null int64
penaltyMinutes          411578 non-null int64
faceOffWins             411578 non-null int64
faceoffTaken            411578 non-null int64
takeaways               411578 non-null int64
giveaways               411578 non-null int64
shortHandedGoals        411578 non-null int64
shortHandedAssists      411578 non-null int64
blocked                 411578 non-null int64
plusMinus               411578 non-null int64
evenTimeOnIce           411578 non-null int64
shortHandedTimeOnIce    411578 non-null int64
powerPlayTimeOnIce      411578 non-null int64
dtypes: int64(22)
memory usage: 69.1 MB

In [5]:
skaterStatsInput

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2011030221,8467412,1,999,0,0,1,3,0,0,...,0,0,0,0,0,0,-1,885,98,16
1,2011030221,8468501,1,1168,0,0,0,4,0,0,...,0,1,1,0,0,1,0,767,401,0
2,2011030221,8470609,1,558,0,0,2,1,0,0,...,2,0,0,0,0,1,-1,542,0,16
3,2011030221,8471816,1,1134,0,0,1,4,0,0,...,0,1,0,0,0,1,-1,935,183,16
4,2011030221,8472410,1,436,0,0,1,3,0,0,...,6,0,0,0,0,0,-1,436,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411573,2018030417,8475807,6,501,0,0,1,2,0,0,...,0,0,0,0,0,0,-1,501,0,0
411574,2018030417,8475149,6,1062,0,0,2,0,0,0,...,1,1,0,0,0,0,-1,957,0,105
411575,2018030417,8475745,6,913,0,0,2,3,0,0,...,11,1,0,0,0,0,0,913,0,0
411576,2018030417,8478443,6,1006,0,0,1,1,0,0,...,0,0,1,0,0,2,-1,1006,0,0
411577,2018030417,8478046,6,909,0,0,2,0,0,0,...,0,1,1,0,0,0,0,909,0,0

In [7]:
gameInput.sort_values(by=['home_team_id','date_time_GMT'])

,game_id,season,type,date_time,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
9779,2010020007,20102011,R,2010-10-08,2010-10-08 23:00:00+00:00,25,1,4,3,away win OT,left,Prudential Center,/api/v1/venues/null,America/New_York,-4,EDT
10380,2010020027,20102011,R,2010-10-11,2010-10-11 20:00:00+00:00,5,1,3,1,away win REG,left,Prudential Center,/api/v1/venues/null,America/New_York,-4,EDT
10540,2010020048,20102011,R,2010-10-15,2010-10-15 23:00:00+00:00,21,1,3,2,away win REG,left,Prudential Center,/api/v1/venues/null,America/New_York,-4,EDT
8866,2010020056,20102011,R,2010-10-16,2010-10-16 23:00:00+00:00,6,1,4,1,away win REG,left,Prudential Center,/api/v1/venues/null,America/New_York,-4,EDT
8903,2010020100,20102011,R,2010-10-23,2010-10-23 23:00:00+00:00,7,1,6,1,away win REG,left,Prudential Center,/api/v1/venues/null,America/New_York,-4,EDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11184,2018021109,20182019,R,2019-03-17,2019-03-17 02:00:00+00:00,22,53,3,2,away win OT,left,Gila River Arena,/api/v1/venues/5043,America/Phoenix,-7,MST
11259,2018021184,20182019,R,2019-03-27,2019-03-27 02:00:00+00:00,16,53,0,1,home win REG,left,Gila River Arena,/api/v1/venues/5043,America/Phoenix,-7,MST
11291,2018021217,20182019,R,2019-03-31,2019-03-31 21:00:00+00:00,30,53,0,4,home win REG,left,Gila River Arena,/api/v1/venues/5043,America/Phoenix,-7,MST
11313,2018021238,20182019,R,2019-04-03,2019-04-03 02:00:00+00:00,26,53,3,1,away win REG,left,Gila River Arena,/api/v1/venues/5043,America/Phoenix,-7,MST
11343,2018021269,20182019,R,2019-04-07,2019-04-07 02:00:00+00:00,52,53,4,2,away win REG,left,Gila River Arena,/api/v1/venues/5043,America/Phoenix,-7,MST

In [3]:
gameInput['date_time_GMT'] = pd.to_datetime(gameInput['date_time_GMT'], errors='coerce')

In [6]:
goalies = goalieInput.loc[:,['game_id','team_id','shots','saves']].groupby(['game_id','team_id']).sum().reset_index()
goalies['percentage'] = (goalies['saves'] / goalies['shots'])*100

In [6]:
gameInput = gameInput.sort_values(by=['game_id'])
gameInput

,game_id,season,type,date_time,date_time_GMT,away_team_id,home_team_id,away_goals,home_goals,outcome,home_rink_side_start,venue,venue_link,venue_time_zone_id,venue_time_zone_offset,venue_time_zone_tz
11078,2010020001,20102011,R,2010-10-07,2010-10-07 23:00:00+00:00,8,10,2,3,home win REG,right,Air Canada Centre,/api/v1/venues/null,America/Toronto,-4,EDT
10725,2010020002,20102011,R,2010-10-07,2010-10-07 23:00:00+00:00,4,5,3,2,away win REG,left,CONSOL Energy Center,/api/v1/venues/null,America/New_York,-4,EDT
9625,2010020003,20102011,R,2010-10-07,2010-10-07 16:00:00+00:00,12,30,4,3,away win REG,right,Hartwall Areena,/api/v1/venues/null,America/Chicago,-5,CDT
10256,2010020004,20102011,R,2010-10-08,2010-10-08 02:00:00+00:00,16,21,3,4,home win OT,right,Pepsi Center,/api/v1/venues/null,America/Denver,-6,MDT
10673,2010020005,20102011,R,2010-10-08,2010-10-08 02:00:00+00:00,20,22,0,4,home win REG,left,Rexall Place,/api/v1/venues/null,America/Edmonton,-6,MDT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11429,2018030413,20182019,P,2019-06-02,2019-06-02 00:00:00+00:00,6,19,7,2,away win REG,left,Enterprise Center,/api/v1/venues/5076,America/Chicago,-5,CDT
11430,2018030414,20182019,P,2019-06-04,2019-06-04 00:00:00+00:00,6,19,2,4,home win REG,left,Enterprise Center,/api/v1/venues/5076,America/Chicago,-5,CDT
11431,2018030415,20182019,P,2019-06-07,2019-06-07 00:00:00+00:00,19,6,2,1,away win REG,left,TD Garden,/api/v1/venues/5085,America/New_York,-4,EDT
11432,2018030416,20182019,P,2019-06-10,2019-06-10 00:00:00+00:00,6,19,5,1,away win REG,left,Enterprise Center,/api/v1/venues/5076,America/Chicago,-5,CDT
11433,2018030417,20182019,P,2019-06-13,2019-06-13 00:00:00+00:00,19,6,4,1,away win REG,left,TD Garden,/api/v1/venues/5085,America/New_York,-4,EDT

In [1]:
games = pd.DataFrame(columns=['game_id', 'season', 'time', 'home_scored', 'home_conceded', 'home_win','home_percentage', 'home_id', 'away_scored', 'away_conceded', 'away_win','away_percentage', 'away_id'])
for index, row in gameInput.iterrows():
    homeS = 0;
    homeC = 0;
    homeW = 0;
    awayS = 0;
    awayC = 0;
    awayW = 0;
    homePerc = 50;
    awayPerc = 50;
    if not (gameInput.loc[((gameInput['home_team_id'] == row['home_team_id']) & (gameInput['date_time_GMT'] < row['date_time_GMT']))].tail(10).empty):
        homeLast = gameInput.loc[((gameInput['home_team_id'] == row['home_team_id']) & (gameInput['date_time_GMT'] < row['date_time_GMT']))].tail(10)
        for index1, game in homeLast.iterrows():
            homeS += game['home_goals']
            homeC += game['away_goals']
            if(game['home_goals'] > game['away_goals']):
                homeW += 1
            if not goalies.loc[(goalies['game_id'] == row['game_id']) & (goalies['team_id'] == row['home_team_id'])].empty:
                homePerc = goalies.loc[(goalies['game_id'] == row['game_id']) & (goalies['team_id'] == row['home_team_id'])]
                homePerc = homePerc['percentage'].values[0]
    if not (gameInput.loc[((gameInput['away_team_id'] == row['away_team_id']) & (gameInput['date_time_GMT'] < row['date_time_GMT']))].tail(10).empty):
        awayLast = gameInput.loc[((gameInput['away_team_id'] == row['away_team_id']) & (gameInput['date_time_GMT'] < row['date_time_GMT']))].tail(10)
        for index1, game in awayLast.iterrows():
            awayS += game['away_goals']
            awayC += game['home_goals']
            if(game['away_goals'] > game['home_goals']):
                awayW += 1
            if not goalies.loc[(goalies['game_id'] == row['game_id']) & (goalies['team_id'] == row['away_team_id'])].empty:
                awayPerc = goalies.loc[(goalies['game_id'] == row['game_id']) & (goalies['team_id'] == row['away_team_id'])]
                awayPerc = awayPerc['percentage'].values[0]
    d = {'game_id': row['game_id'], 'season': row['season'], 'time': row['date_time_GMT'], 'home_scored': homeS, 'home_conceded': homeC, 'home_win': homeW, 'home_percentage': homePerc, 'home_id':row['home_team_id'], 'away_scored': awayS, 'away_conceded': awayC, 'away_win': awayW, 'away_percentage': awayPerc, 'away_id': row['away_team_id']}
    games.at[index, :] = d
#     print(row['game_id'])

NameError: name 'pd' is not defined

In [8]:
games.sort_values(by=['home_id', 'time']).head(20)

,game_id,season,time,home_scored,home_conceded,home_win,home_percentage,home_id,away_scored,away_conceded,away_win,away_percentage,away_id
9779,2010020007,20102011,2010-10-08 23:00:00+00:00,0,0,0,50,1,0,0,0,50,25
10380,2010020027,20102011,2010-10-11 20:00:00+00:00,3,4,0,93.3333,1,0,0,0,50,5
10540,2010020048,20102011,2010-10-15 23:00:00+00:00,4,7,0,86.3636,1,7,8,1,95.3488,21
8866,2010020056,20102011,2010-10-16 23:00:00+00:00,6,10,0,88.5714,1,0,0,0,50,6
8903,2010020100,20102011,2010-10-23 23:00:00+00:00,7,14,0,79.3103,1,5,5,1,96.2963,7
9578,2010020179,20102011,2010-11-05 23:00:00+00:00,8,20,0,85,1,18,16,4,100,3
9129,2010020211,20102011,2010-11-11 00:00:00+00:00,8,23,0,90.4762,1,17,18,3,87.5,7
10703,2010020227,20102011,2010-11-13 00:00:00+00:00,12,28,0,87.5,1,23,35,2,89.7436,22
8738,2010020299,20102011,2010-11-23 00:00:00+00:00,16,31,1,100,1,22,16,4,78.2609,15
10914,2010020313,20102011,2010-11-25 00:30:00+00:00,21,31,2,96.1538,1,22,25,3,95.2381,20
10005,2010020334,20102011,2010-11-27 18:00:00+00:00,23,32,3,97.561,1,31,21,6,96,4
10061,2010020367,20102011,2010-12-03 00:00:00+00:00,22,29,4,84.375,1,21,16,6,96.4286,8
9882,2010020428,20102011,2010-12-12 00:00:00+00:00,22,31,4,82.6087,1,26,21,6,97.0588,17
10168,2010020450,20102011,2010-12-16 00:00:00+00:00,21,32,4,100,1,28,23,7,89.6552,27
9450,2010020469,20102011,2010-12-18 00:00:00+00:00,23,28,5,85,1,26,29,5,93.75,18
10203,2010020508,20102011,2010-12-24 00:00:00+00:00,23,25,5,64.2857,1,11,42,0,97.1429,2
10188,2010020520,20102011,2010-12-27 00:00:00+00:00,24,27,5,81.8182,1,16,35,2,96.6667,10
10815,2010020545,20102011,2010-12-30 00:00:00+00:00,21,26,5,92,1,31,29,6,97.7273,3
9973,2010020557,20102011,2010-12-31 22:00:00+00:00,18,26,4,96.5517,1,32,34,5,89.2857,11
10474,2010020586,20102011,2011-01-05 00:00:00+00:00,16,27,4,88.8889,1,29,32,5,95.4545,30

In [11]:
games.to_csv('.\datasets\dataset41.csv', encoding='utf-8', index=False)